### ISSUE TITLE
New features to get to a 1.0.0 release

### ISSUE THREAD

**Issue by dearchap** [urfave/sflags#39]
## Checklist

* [x] Are you running the latest v3 release? The list of releases is [here](https://github.com/urfave/sflags/releases).
* [x] Did you perform a search about this feature? Here's the [GitHub guide](https://help.github.com/en/github/managing-your-work-on-github/using-search-to-filter-issues-and-pull-requests) about searching.

## What problem does this solve?

Following features would be useful to get a full featured release

- [x] Add Required Flag tag #40 
- [ ] ~~Add support for Viper #6  #~~
- [ ] Add support for map values #7 
- [ ] Add support for multiple env vars #41 
- [ ] Flag Type for setting date using natural language #8 (https://github.com/olebedev/when)
